# Generated by Django 4.1.4 on 2022-12-25 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_upvote_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_commented',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post'),
        ),
    ]
