# Generated by Django 4.1.4 on 2022-12-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsletter_alter_contact_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(upload_to='mailtemplates/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
