# Generated by Django 4.1.4 on 2022-12-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_htmltemplates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmltemplates',
            name='template',
            field=models.FileField(blank=True, null=True, upload_to='mailtemplates/'),
        ),
    ]
