# Generated by Django 4.1.4 on 2022-12-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_htmltemplates_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmltemplates',
            name='template',
            field=models.FileField(blank=True, null=True, upload_to='C:\\Users\\fraan\\Desktop\\practica\\blog\\backend\\core/templates\\'),
        ),
    ]
