# Generated by Django 4.1.4 on 2023-01-09 18:03

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_htmltemplates_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmltemplates',
            name='template',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/runner/djangoblog-1/backend/core/templates/'), upload_to=''),
        ),
    ]
